[project]
name = "mlops-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlflow>=3.7.0",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "pymango>=0.1.1",
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.8.0",
    "setuptools>=80.9.0",
]
